name: "notify"
version: "0.0.8"
repository: github.com/madflow/trivy-plugin-notify
maintainer: madflow
summary: Vulnerability notification
description: |-
  Trivy plugin for sending notifications to one or more supported providers.
  Currently supports slack and webhook.
output: true
platforms:
  - selector:
      os: darwin
      arch: amd64
    uri: https://github.com/madflow/trivy-plugin-notify/releases/download/v0.0.8/trivy_plugin_notify_0.0.8_darwin-amd64.tar.gz
    bin: ./notify
  - selector:
      os: darwin
      arch: arm64
    uri: https://github.com/madflow/trivy-plugin-notify/releases/download/v0.0.8/trivy_plugin_notify_0.0.8_darwin-arm64.tar.gz
    bin: ./notify
  - selector:
      os: linux
      arch: amd64
    uri: https://github.com/madflow/trivy-plugin-notify/releases/download/v0.0.8/trivy_plugin_notify_0.0.8_linux-amd64.tar.gz
    bin: ./notify
  - selector:
      os: linux
      arch: arm64
    uri: https://github.com/madflow/trivy-plugin-notify/releases/download/v0.0.8/trivy_plugin_notify_0.0.8_linux-arm64.tar.gz
    bin: ./notify
