name: Install test
on:
  schedule:
    - cron: "0 8 * * *"
  workflow_dispatch:

jobs:
  build:
    name: Install test (Trivy ${{ matrix.trivy-version }})
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false
      matrix:
        trivy-version: ['v0.57.1', 'v0.63.0']
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Install Trivy ${{ matrix.trivy-version }}
        env:
          TRIVY_DB_REPOSITORY: public.ecr.aws/aquasecurity/trivy-db,aquasec/trivy-db,ghcr.io/aquasecurity/trivy-db
          TRIVY_JAVA_DB_REPOSITORY: public.ecr.aws/aquasecurity/trivy-java-db,aquasec/trivy-java-db,ghcr.io/aquasecurity/trivy-java-db
        uses: aquasecurity/setup-trivy@v0.2.3 
        with:
          version: ${{ matrix.trivy-version }}
      - name: Install Plugin
        run: |
          trivy plugin install github.com/madflow/trivy-plugin-notify
      - name: Run Trivy with plugin
        run: trivy fs -f json -o plugin=notify --output-plugin-arg "--providers=console" .
